language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
before_install:
  - sudo apt-get update
  - sudo apt-get install libkrb5-dev
before_script:
  - npm install -g bower grunt-cli
  - bower install
services: mongodb
